// <auto-generated />
using System;
using DaibucatAntonia_CherechesIlincaMaria.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DaibucatAntonia_CherechesIlincaMaria.Migrations
{
    [DbContext(typeof(DaibucatAntonia_CherechesIlincaMariaContext))]
    partial class DaibucatAntonia_CherechesIlincaMariaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DaibucatAntonia_CherechesIlincaMaria.Models.Abonament", b =>
                {
                    b.Property<int>("AbonamentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AbonamentId"));

                    b.Property<string>("Descriere")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeAbonament")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Pret")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("AbonamentId");

                    b.ToTable("Abonament");
                });

            modelBuilder.Entity("DaibucatAntonia_CherechesIlincaMaria.Models.AbonamentClient", b =>
                {
                    b.Property<int>("AbonamentClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AbonamentClientId"));

                    b.Property<int>("AbonamentId")
                        .HasColumnType("int");

                    b.Property<bool>("Activ")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DataInceput")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataSfarsit")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("AbonamentClientId");

                    b.HasIndex("AbonamentId");

                    b.HasIndex("UserId");

                    b.ToTable("AbonamentClient");
                });

            modelBuilder.Entity("DaibucatAntonia_CherechesIlincaMaria.Models.ClasaFitness", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Antrenor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descriere")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeClasa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Ora")
                        .HasColumnType("datetime2");

                    b.Property<string>("Zi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ClasaFitness");
                });

            modelBuilder.Entity("DaibucatAntonia_CherechesIlincaMaria.Models.Plata", b =>
                {
                    b.Property<int>("PlataId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlataId"));

                    b.Property<int>("AbonamentClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataPlata")
                        .HasColumnType("datetime2");

                    b.Property<string>("MetodaPlata")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Suma")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("PlataId");

                    b.HasIndex("AbonamentClientId");

                    b.ToTable("Plata");
                });

            modelBuilder.Entity("DaibucatAntonia_CherechesIlincaMaria.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParolaHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenume")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("DaibucatAntonia_CherechesIlincaMaria.Models.AbonamentClient", b =>
                {
                    b.HasOne("DaibucatAntonia_CherechesIlincaMaria.Models.Abonament", "Abonament")
                        .WithMany("AbonamenteClient")
                        .HasForeignKey("AbonamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DaibucatAntonia_CherechesIlincaMaria.Models.User", "User")
                        .WithMany("AbonamenteClient")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Abonament");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DaibucatAntonia_CherechesIlincaMaria.Models.Plata", b =>
                {
                    b.HasOne("DaibucatAntonia_CherechesIlincaMaria.Models.AbonamentClient", "AbonamentClient")
                        .WithMany("Plati")
                        .HasForeignKey("AbonamentClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AbonamentClient");
                });

            modelBuilder.Entity("DaibucatAntonia_CherechesIlincaMaria.Models.Abonament", b =>
                {
                    b.Navigation("AbonamenteClient");
                });

            modelBuilder.Entity("DaibucatAntonia_CherechesIlincaMaria.Models.AbonamentClient", b =>
                {
                    b.Navigation("Plati");
                });

            modelBuilder.Entity("DaibucatAntonia_CherechesIlincaMaria.Models.User", b =>
                {
                    b.Navigation("AbonamenteClient");
                });
#pragma warning restore 612, 618
        }
    }
}
